#!/usr/bin/env bash
# Using your debugging skills,
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default; sudo service nginx restart
